spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/heroku_df2033176d61b3d?useSSL=false&serverTimezone=UTC&reconnect=true
    username: b65e4109baf036
    password: 1428af9d
    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect